export const questions = [
  "A JS value that doesn't change.",
  'A function that is passed as an argument to another function and is executed after the parent function has finished executing.',
  'A block of code designed to perform a particular task.',
  'A finite sequence of well-defined, computer-implementable instructions, typically to solve a class of specific problems or to perform a computation.',
  'The meaning of words, phrases, sentences, or symbols in the context of a particular language or system.',
  "A function that has access to its own scope, the outer function's scope, and the global scope.",
  'A strongly typed superset of JavaScript.',
  'A function calling itself while some condition is true.',
  'A keyword that allows asynchronous code to be written in a synchronous manner.',
  'A feature that allows you to unpack values from arrays, or properties from objects, into distinct variables.',
  'An object representing the eventual completion or failure of an asynchronous operation.',
  'A function that responds to events triggered by the user.',
  'The process of finding and fixing errors in code.',
  'A process to convert modern JavaScript code to an older version for browser compatibility.',
  'Code that provides functionality to older browsers lacking support for certain features.',
  'A web application that dynamically updates content without full page reloads.',
  'A software application that interprets HTML documents and displays them in a human-readable format',
  'A technique where a function with multiple arguments is transformed into a sequence of functions, each with a single argument',
  'A central location where the complete history of all versions of the project files are stored',
]
